### ISSUE TITLE
'Avoid unnecessary gendered language' link on CONTRIBUTING.md is broken

### ISSUE THREAD

**Issue by hanbyul-here** [mapschool/mapschool#114]
Current link (http://writingcenter.unc.edu/handouts/gender-sensitive-language/) returns 404. I wonder the page is moved to this one? http://writingcenter.unc.edu/handouts/gender-inclusive-language/

**Comment by tmcw** [comment]
Indeed, thanks @hanbyul-here! Fixed the link
