### ISSUE TITLE
Make headings easily linkable

### ISSUE THREAD

**Issue by kannes** [mapschool/mapschool#117]
While headings have id attributes already (for example https://mapschool.io/#raster-bands), their existence is not exposed to the user.

It would be great if headings would advertise their "shareability" on mouseover just like e.g. on the README.md when rendered by GitHub: https://github.com/mapschool/mapschool (hover "License" and you will see an anchor icon appear that you can click)

I am not sure what the best way would be. Googling around suggested mostly JavaScript solutions which I would consider a bad compromise. Maybe this could be done in the Markdown -> HTML processing step? I wanted to add it via CSS but failed.

**Comment by kannes** [comment]
The JS turned out to be trivial and trivial to add to an existing loop over all the headines so I made https://github.com/mapschool/mapschool/pull/118

**Comment by tmcw** [comment]
Cool, thanks!
