### ISSUE TITLE
mapschool.io domain may need renewal?

### ISSUE THREAD

**Issue by mapninja** [mapschool/mapschool#125]
https://mapschool.io throwing error page from cloudflare when trying to access:

_If you're the owner of this website:_

_Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522)_

**Comment by tmcw** [comment]
Thanks for the heads-up, I had transferred my domains from Gandi to Cloudflare and that combined with previously using Netlify for some of the nameservers created some mess… and anyway, fixed now!
