### ISSUE TITLE
i18n guidelines

### ISSUE THREAD

**Issue by miguelpeixe** [mapschool/mapschool#15]
Hi Tom,

I want to translate this resource to pt-BR, do you have any guideline for that to be integrated with your rep?

**Comment by tmcw** [comment]
Awesome, [added a note about translations](https://github.com/tmcw/mapschool/blob/gh-pages/CONTRIBUTING.md#translation) with a first approach to try, but open to any better ways to do it that still keep it simple!

**Comment by miguelpeixe** [comment]
Great, thanks a lot for this resource. You think it would be ok to republish on our project, [Geojournalism Handbook](http://geojournalism.oeco.org.br/)?

**Comment by tmcw** [comment]
Absolutely, go for it!

**Comment by tmcw** [comment]
Cool, ping back if there's anything to add in terms of translations.
