### ISSUE TITLE
Geometric operations

### ISSUE THREAD

**Issue by tmcw** [mapschool/mapschool#29]
union / intersection / buffer / and so on

are these core? unclear

**Comment by morganherlocker** [comment]
I think so. These are all essential for any work with polygon data. I would add difference as well (sometimes referred to as 'erase'; not sure which term is more common).

**Comment by vlasvlasvlas** [comment]
Got lot of interest example with postgis. If you want i can work in this.

Boundless has also lots of graphic examples:

http://workshops.boundlessgeo.com/postgis-intro/index.html

http://workshops.boundlessgeo.com/postgis-intro/spatial_relationships.html

more
http://workshops.boundlessgeo.com/#tutorials

**Comment by tmcw** [comment]
While these are super useful for GIS, they aren't so essential for "maps" that I'm putting them on my "personal todo list". Happy to accept a PR if someone else wants to write and illustrate this section.
