### ISSUE TITLE
exercises

### ISSUE THREAD

**Issue by tmcw** [mapschool/mapschool#35]

**Comment by lyzidiamond** [comment]
Are you looking for someone to write up exercises you've already thought of, or are you wanting exercises born out of what you've written? I've got a couple ideas.

**Comment by tmcw** [comment]
I have no clear ideas here, only an inkling it might be cool: if you have ideas, please go for it!

**Comment by tmcw** [comment]
This would be weird. Constructed exercises, nah.

**Comment by wboykinm** [comment]
Good god; platform-agnostic exercises! Gah!
