### ISSUE TITLE
Better translation workflow

### ISSUE THREAD

**Issue by sabas** [mapschool/mapschool#43]
What about creating po files from README.md foreach commit?
For instance http://po4a.alioth.debian.org/

**Comment by tmcw** [comment]
I'm not too familiar with PO or how I would get that to be automated - is PO mostly used so that people can use translation software?

**Comment by sabas** [comment]
The po files are generated to manage translations for projects using gettext (http://www.gnu.org/software/gettext/) for internationalization -like Wordpress for example-, and for crowdsourced projects (see for example http://crowdin.net/ as a portal).
From project manager side one can simply update the source file (Crowdin has a command line utility http://crowdin.net/page/cli-tool) and translators can detect which rows need update or translation (if not on a web portal, with programs like POEdit http://www.poedit.net/).

Never tried with a document before...

**Comment by tmcw** [comment]
Since this is just one big document, rather than chunks of text that need translation, I think it might be doable to translate without using PO or similar, like how Wikipedia keeps translated versions of pages.

**Comment by tmcw** [comment]
Today I reworked this project to make it use jekyll - this should simplify translation workflows since there's no more manual build step & an `index.es.md` should just automatically work.

**Comment by tmcw** [comment]
Closing - po would be an odd fit for full-translations like this one I think.
