### ISSUE TITLE
More about projections

### ISSUE THREAD

**Issue by tmcw** [mapschool/mapschool#56]
http://www.metafilter.com/136346/mapschool#5406768

People love projections. Likely candidate for expando-section

**Comment by sabas** [comment]
http://xkcd.com/977/

**Comment by tmcw** [comment]
Let's stay far away from the xkcd tone :)

**Comment by Bakelly** [comment]
How about:

Geographers HATE him!!!
This one WEIRD trick will shrink the apparent size of Greenland 3X!!!

**Comment by sabas** [comment]
http://www.progonos.com/furuti/MapProj/Normal/TOC/cartTOC.html A suggestion for further readings section by @aborruso

**Comment by sabas** [comment]
Leaving this here
http://pubs.er.usgs.gov/publication/pp1453

I don't know how much in depth we should go on each topic if it would still be an 'introduction...

**Comment by vlasvlasvlas** [comment]
+1
