### ISSUE TITLE
Smoosh?

### ISSUE THREAD

**Issue by sabas** [mapschool/mapschool#67]
Only to ask what's the meaning of 'smoosh', it's a slang term I assume, but don't think that's the meaning provided by [Urbandictionary](http://www.urbandictionary.com/define.php?term=smoosh) lol

I interpreted as a colloquial form for smash (I'm translating into italian)

**Comment by tmcw** [comment]
Yep, in this usage it's equivalent to smash and an alternative spelling of [smush](http://dictionary.reference.com/browse/smush)

**Comment by sabas** [comment]
ok thanks.
