### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by tmcw** [mapschool/mapschool#74]
@yaph @jsanz @moiarcsan @aitorfreire @rteijeiro @juanluisrp

Hey: you may have noticed I merged & linked up the spanish translation, since it's great and should be on the site! Since I know there are still things you might want to tweak, I've given you all commit access to this repository so you can change things directly.

**Comment by jsanz** [comment]
Cool @tmcw I'll finish the translation directly on your repo then, there are a couple of paragraphs to do.

Thanks!!
