### ISSUE TITLE
CC-BY3.0? or CC0?

### ISSUE THREAD

**Issue by nyampire** [mapschool/mapschool#89]
As index.md says, this is "Creative Commons Attribution 3.0 Unported".
But as CONTRIBUTING.md and other texts say this is "CC0".

Which is proper License for this doc?

**Comment by tmcw** [comment]
I initially had it as "Creative Commons Attribution 3.0 Unported" - I think CC0 would be better, though, since it's simpler and easy to know if you have to attribute a small excerpt.

**Comment by nyampire** [comment]
I prefer CC0, too.
If there are no objection from contributors, could we move to CC0 entirely?

**Comment by tmcw** [comment]
Other contributors, anyone want to ixnay moving to CCO? This would drop the attribution requirement for users of mapschool and make the license the same as Public Domain within the USA. With CC0 we'd have simpler, freer licensing and make it easy and friction-free to, for instance, excerpt mapschool in handouts or class exercises.

/cc @sabas @jsanz @aitorfreire @mizmay @ericfischer @juanluisrp @morganherlocker @Adrianod @cspanring @rubiojr @yaph @wboykinm @wrobstory @moiarcsan @daguar

**Comment by wboykinm** [comment]
Big fan of CC0. Go for it.

**Comment by daguar** [comment]
No problem from me!

On Thu, Sep 11, 2014 at 7:13 PM, Bill Morris notifications@github.com
wrote:

> Big fan of CC0. Go for it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tmcw/mapschool/issues/89#issuecomment-55353902.

## 

Dave Guarino
Consultant, Health Vertical
(2013 Fellowship alumnus)
Code for America http://www.codeforamerica.org/
dave@codeforamerica.org
LinkedIn http://www.linkedin.com/in/daveguarino/ | GitHub
https://github.com/daguar/

**Comment by sabas** [comment]
No problem at all!

**Comment by jsanz** [comment]
El 12/09/14 a las #4, Tom MacWright escribió:

> Other contributors, anyone want to ixnay moving to CCO? This would drop
> the attribution requirement for users of mapschool and make the license
> the same as Public Domain within the USA. With CC0 we'd have simpler,
> freer licensing and make it easy and friction-free to, for instance,
> excerpt mapschool in handouts or class exercises.

+1 Jorge

## 

Jorge Gaspar Sanz Salinas
http://es.osgeo.org
http://jorgesanz.net

**Comment by moiarcsan** [comment]
No problem! It's ok

**Comment by juanluisrp** [comment]
For me [CC0](https://creativecommons.org/choose/zero) is OK.

**Comment by Adrianod** [comment]
No problem.

**Comment by rteijeiro** [comment]
:+1:

**Comment by cspanring** [comment]
CC0 is OK.
