### ISSUE TITLE
The unity of data

### ISSUE THREAD

**Issue by tmcw** [mapschool/mapschool#9]

**Comment by morganherlocker** [comment]
Any clarification on this item? Is this addressing combining multiple datasets that share some commonality (2 zip code layers that you could join by zip/ merging a bunch of zip codes that were previously separated by state/ etc.), or are you talking about data in a more abstract way?

**Comment by tmcw** [comment]
Definitely a little vague: what I was thinking originally was something akin to talking about [information theory](http://en.wikipedia.org/wiki/Information_theory) in the scope of geo: emphasize how formats are just the particulars of how things are stored and there are ways to store raster data as vector and vice-versa to some degree.

But talking about merging would probably be way more practical / doable :)

**Comment by tmcw** [comment]
Too weird a topic to be actionable.
